### ISSUE TITLE
Could not pass event BlockBreakEvent to MineTinker v1.6.2

### ISSUE THREAD

**Issue by Frodwo** [Flo56958/MineTinker#182]
[12:08:06] [Server thread/ERROR]: Could not pass event BlockBreakEvent to MineTinker v1.6.2
java.lang.NullPointerException: null
	at de.flo56958.minetinker.listeners.BlockListener.onBlockBreak(BlockListener.java:146) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor232.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-966]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-966]
	at de.flo56958.minetinker.utils.data.DataHandler.playerBreakBlock(DataHandler.java:103) ~[?:?]
	at de.flo56958.minetinker.modifiers.types.Timber.lambda$breakTree$2(Timber.java:213) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1370) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1283) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-966]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[12:08:06] [Server thread/ERROR]: Could not pass event BlockBreakEvent to MineTinker v1.6.2
java.lang.NullPointerException: null
	at de.flo56958.minetinker.listeners.BlockListener.onBlockBreak(BlockListener.java:146) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor232.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-966]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-966]
	at de.flo56958.minetinker.utils.data.DataHandler.playerBreakBlock(DataHandler.java:103) ~[?:?]
	at de.flo56958.minetinker.modifiers.types.Timber.lambda$breakTree$2(Timber.java:213) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1370) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1283) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-966]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[12:08:06] [Server thread/ERROR]: Could not pass event BlockBreakEvent to MineTinker v1.6.2
java.lang.NullPointerException: null
	at de.flo56958.minetinker.listeners.BlockListener.onBlockBreak(BlockListener.java:146) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor232.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-966]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-966]
	at de.flo56958.minetinker.utils.data.DataHandler.playerBreakBlock(DataHandler.java:103) ~[?:?]
	at de.flo56958.minetinker.modifiers.types.Timber.lambda$breakTree$2(Timber.java:213) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1370) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1283) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-966]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[12:08:06] [Server thread/ERROR]: Could not pass event BlockBreakEvent to MineTinker v1.6.2
java.lang.NullPointerException: null
	at de.flo56958.minetinker.listeners.BlockListener.onBlockBreak(BlockListener.java:146) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor232.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-966]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-966]
	at de.flo56958.minetinker.utils.data.DataHandler.playerBreakBlock(DataHandler.java:103) ~[?:?]
	at de.flo56958.minetinker.modifiers.types.Timber.lambda$breakTree$2(Timber.java:213) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1370) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1283) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-966]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[12:08:06] [Server thread/ERROR]: Could not pass event BlockBreakEvent to MineTinker v1.6.2
java.lang.NullPointerException: null
	at de.flo56958.minetinker.listeners.BlockListener.onBlockBreak(BlockListener.java:146) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor232.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-966]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-966]
	at de.flo56958.minetinker.utils.data.DataHandler.playerBreakBlock(DataHandler.java:103) ~[?:?]
	at de.flo56958.minetinker.modifiers.types.Timber.lambda$breakTree$2(Timber.java:213) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1370) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1283) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-966]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[12:08:06] [Server thread/ERROR]: Could not pass event BlockBreakEvent to MineTinker v1.6.2
java.lang.NullPointerException: null
	at de.flo56958.minetinker.listeners.BlockListener.onBlockBreak(BlockListener.java:146) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor232.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-966]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-966]
	at de.flo56958.minetinker.utils.data.DataHandler.playerBreakBlock(DataHandler.java:103) ~[?:?]
	at de.flo56958.minetinker.modifiers.types.Timber.lambda$breakTree$2(Timber.java:213) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1370) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1283) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-966]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[12:08:06] [Server thread/ERROR]: Could not pass event BlockBreakEvent to MineTinker v1.6.2
java.lang.NullPointerException: null
	at de.flo56958.minetinker.listeners.BlockListener.onBlockBreak(BlockListener.java:146) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor232.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-966]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-966]
	at de.flo56958.minetinker.utils.data.DataHandler.playerBreakBlock(DataHandler.java:103) ~[?:?]
	at de.flo56958.minetinker.modifiers.types.Timber.lambda$breakTree$2(Timber.java:213) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1370) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1283) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-966]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[12:08:06] [Server thread/ERROR]: Could not pass event BlockBreakEvent to MineTinker v1.6.2
java.lang.NullPointerException: null
	at de.flo56958.minetinker.listeners.BlockListener.onBlockBreak(BlockListener.java:146) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor232.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-966]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-966]
	at de.flo56958.minetinker.utils.data.DataHandler.playerBreakBlock(DataHandler.java:103) ~[?:?]
	at de.flo56958.minetinker.modifiers.types.Timber.lambda$breakTree$2(Timber.java:213) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1370) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1283) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-966]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[12:08:06] [Server thread/ERROR]: Could not pass event BlockBreakEvent to MineTinker v1.6.2
java.lang.NullPointerException: null
	at de.flo56958.minetinker.listeners.BlockListener.onBlockBreak(BlockListener.java:146) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor232.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-966]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-966]
	at de.flo56958.minetinker.utils.data.DataHandler.playerBreakBlock(DataHandler.java:103) ~[?:?]
	at de.flo56958.minetinker.modifiers.types.Timber.lambda$breakTree$2(Timber.java:213) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1370) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1283) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-966]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[12:08:06] [Server thread/ERROR]: Could not pass event BlockBreakEvent to MineTinker v1.6.2
java.lang.NullPointerException: null
	at de.flo56958.minetinker.listeners.BlockListener.onBlockBreak(BlockListener.java:146) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor232.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-966]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-966]
	at de.flo56958.minetinker.utils.data.DataHandler.playerBreakBlock(DataHandler.java:103) ~[?:?]
	at de.flo56958.minetinker.modifiers.types.Timber.lambda$breakTree$2(Timber.java:213) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1370) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1283) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-966]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[12:08:06] [Server thread/ERROR]: Could not pass event BlockBreakEvent to MineTinker v1.6.2
java.lang.NullPointerException: null
	at de.flo56958.minetinker.listeners.BlockListener.onBlockBreak(BlockListener.java:146) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor232.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-966]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-966]
	at de.flo56958.minetinker.utils.data.DataHandler.playerBreakBlock(DataHandler.java:103) ~[?:?]
	at de.flo56958.minetinker.modifiers.types.Timber.lambda$breakTree$2(Timber.java:213) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Purpur-966]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1370) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1283) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.5.jar:git-Purpur-966]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-966]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Flo56958** [comment]
for now just reconnect to the server, the bug is already fixed
