### ISSUE TITLE
Error output

### ISSUE THREAD

**Issue by palipajo** [Flo56958/MineTinker#8]
[13:41:26] [Server thread/ERROR]: Could not pass event InventoryClickEvent to MineTinker va4
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-69774b3-6997012]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-69774b3-6997012]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-69774b3-6997012]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-69774b3-6997012]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2130) ~[spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-69774b3-6997012]
	at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-69774b3-6997012]
	at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-69774b3-6997012]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-69774b3-6997012]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-69774b3-6997012]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-69774b3-6997012]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-69774b3-6997012]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-69774b3-6997012]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-69774b3-6997012]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at de.flo56958.MineTinker.Listeners.AnvilListener.onInventoryClick(AnvilListener.java:29) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-69774b3-6997012]
	... 15 more

**Comment by Flo56958** [comment]
@palipajo 
I think you put the items into the anvil in the "wrong" order (for the plugin). I fixed this problem in the next update, but i do not think this bug is gamebreaking and therefore it is not necessary to update the plugin just for this error.

Flo56958
