### ISSUE TITLE
The Anvil doesn't work.

### ISSUE THREAD

**Issue by Juessa** [Flo56958/MineTinker#9]
Hi, an error happen when I try to put the modifier in the anvil, it doesn't work, and gives this error message:

![2018-08-03_10 45 32](https://user-images.githubusercontent.com/21699137/43652650-6786e6ee-970b-11e8-8974-ebd01ae1b972.png)

 [11:48:20] [Server thread/ERROR]: Could not pass event InventoryClickEvent to MineTinker va4
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2130) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
at de.flo56958.MineTinker.Listeners.AnvilListener.onInventoryClick(AnvilListener.java:29) ~[?:?]
at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
... 15 more

**Comment by Flo56958** [comment]
Issue resolved in a5
